### ISSUE TITLE
Prodekanus dokumentation

### ISSUE THREAD

**Issue by neic** [TK-IT/meta#12]
Lav en wiki side om prodekanus.

- Bagrund for hvorfor den eksisterer
- Hvem man skal i kontakt med hvis noget går galt (AUIT)
- Hvem der har adgang
- Hvad der kører der på med link til dokumentationen for de ting

**Comment by Mortal** [comment]
Jeg har oprettet https://github.com/TK-IT/meta/wiki/Prodekanus. Feedback er velkommen!
