### ISSUE TITLE
Søge på titler på adminsiden

### ISSUE THREAD

**Issue by tjavsi** [TK-IT/meta#16]
SEKR synes INKA-programmets søge funktion på personer er super smart, og kunne godt tænke sig en lignende funktion på TAAGEKAMMERET.DK/admin. Og gerne en måde sådan man kan bruge denne søgefunktion til at tilføje folk til maillister. 

Den smarte funktion er at man kan søge "FUHI" også kommer alle titler op, med korrekt prefix for både FU og VC.

**Comment by neic** [comment]
https://github.com/TK-IT/web/issues/106 tracker allerede denne funktionalitet.
