### ISSUE TITLE
Sende @TAAGEKAMMERET.dk mail fra personlige mailklienter

### ISSUE THREAD

**Issue by neic** [TK-IT/meta#2]
BEST og andre vil gerne kunde sende mail med deres @TAAGEKAMMERET.dk mailadresse i From-header fra deres mailklienter. Gmail kunne tidligere gøre det, men kræver nu en SMTP-server at sende det igennem.

----
Der står en masse på Rizzoma, som ikke rigtigt længere er relevant.

Rav skriver dec 2016:
> Nanoramas tekniske ansvarlige har lige spurgt mig hvordan det går med dette. Jeg har sagt at det kommer på sigt.

**Comment by Mortal** [comment]
Jeg har sat mailkonti op til BEST og sendt en mail til dem med instruktioner.

**Comment by Mortal** [comment]
BEST har taget det i brug - det virker bare. Konfiguration af `postfix-accounts.cf` er dokumenteret på wiki-siden [Postfix og venner](https://github.com/TK-IT/meta/wiki/Postfix-og-venner).
