### ISSUE TITLE
RSS feed til nye albums

### ISSUE THREAD

**Issue by tyilo** [TK-IT/meta#23]
Som bruger, synes jeg at det kunne være rart, hvis der var en måde at blive notifikeret på, når der bliver udgivet nye album (eller måske billeder) på hjemmesiden.

Jeg tænker at et RSS feed med all nye album kunne være en nem og god løsning.

**Comment by Mortal** [comment]
Det er en fin idé - det havde den gamle hjemmeside også. Vil du oprette feature request i web repoet i stedet?

Mht. implementation har Mat/Fys-Tutorgruppens hjemmeside noget kode til at generere RSS-feed så vidt jeg husker til nyheder.
