### ISSUE TITLE
Gamle issues fra merge-apps

### ISSUE THREAD

**Issue by neic** [TK-IT/meta#28]
Efter vi har [merged regnskab og krydsliste](https://github.com/TK-IT/web/commit/512d21018dfa1a4742d4e6ff796866b01213e288) ind i web og mothballed de to repoer har vi nogle issues som ikke er migreret:

19 i [regnskab](https://github.com/TK-IT/regnskab/issues)
3 i [uniprint](https://github.com/TK-IT/uniprint/issues)

De fleste har ingen diskussion og er lavet af @Mortal.

Jeg ser to muligheder: 
1. Vi kan lade dem blive og fortsætte diskussionen der.
2. Vi kan, lige som med dem fra Rizzoma, flytte dem til web og meta.

Jeg hælder mest til 2, så er der færre steder at holde øje. 

Uanset hvad tror jeg en del af dem kunne lukkes. Hvis @Mortal rydder lidt op, skal jeg nok flytte dem.

**Comment by neic** [comment]
Når der er ryddet op kan begge repoer arkiveres under settings/Danger Zone.

**Comment by Mortal** [comment]
Jeg har flyttet/lukket alle issues og PRs i de to repoer.

**Comment by neic** [comment]
De er hermed arkiveret.
