### ISSUE TITLE
/Pictures på prodekanus er 97% fyldt

### ISSUE THREAD

**Issue by neic** [TK-IT/meta#29]

**Comment by Mortal** [comment]
Jeg bad Michael Glad om at udvide den, og han svarede mandag morgen: "jeg har skruet 128G ekstra på /Pictures. Så skulle  der være til lidt flere billeder :)
Teknisk udvidede jeg serveren med en ekstra disk og tilføjede den til BigSpace VG og udvidede filsystemet."
