### ISSUE TITLE
Evaluerings wiki

### ISSUE THREAD

**Issue by neic** [TK-IT/meta#3]
FUHI skriver i 2015:
> Hver bruger har forskelligt adgang til at se ting.
> Eksempler:
> Alle fra BEST kan se det hele.
> VC se hemmelige ting der sker i CERMLAUGET
> Der kan genereres link eller brugere til hængerarangementer så dem der arrangerer det kan se og rette en evaluering.
> 
> Der er også information på alle sider som alt efter hvem der er logget ind er skjult, men kan findes frem med et klik på et +. Eksempelvis er der informationer om bordopstilling til en fest, men det er sjkult for alle andre end FORM.
> 
> Sider har en udløbsdato. Hvis den er overskedet kan man se det i en rapport. Efter en side er blevet opdaterert laver man en ny udløbsdato. Efter en BESTperiode tjekker man rapporten om der er noget der mangler. Se https://www.mediawiki.org/wiki/Extension:FlaggedRevs
> 
> En BEST-post skal have ansvaret for at det hængernes tilføjelser overholder en code of conduct.

Kundeservice skriver i 2015:
> Der er en vis udfordring for en BEST ift. at nå igennem en wiki hvert år for at sikre, at alt indhold er opdateret, idet en wiki ikke er monolitisk. Men jeg er også gammel.

**Comment by Mortal** [comment]
INKA 17/18 skriver: "Vi synes det lyder som en god idé. Grunden er at de flest af os har fået eval sent, og tænker det skyldes at man skal sende en færdig PDF."

**Comment by Mortal** [comment]
Nu hvor vi er blevet Docker-eksperter(-ish), synes jeg vi skal undersøge om ShareLaTeX kan bruges som evalueringswiki. Det har nemlig et officielt Docker-image: https://github.com/sharelatex/sharelatex/wiki/Quick-Start-Guide

Edit to add: Der er selvfølgelig også et officielt MediaWiki-image: https://www.mediawiki.org/wiki/Docker

**Comment by neic** [comment]
Polyteknisk Forening ved DTU (10x kammerets størrelse) er ved at undersøge hvad det kræver at få samlet alle deres overleveringer (evalueringer for enkelte arrangementer) i en wiki. Der findes allerede en wiki for [Studiestarten](https://studiestartswiki.pf.dk/) (parallel til tutorforeningen) og en for [Software-Matematik Rådet](https://github.com/SMRaadet/Overlevering/wiki) (parallel til MFSR og dele af kammeret). Jeg følger arbejdet og ser hvilke erfaringer der kommer ud af det.

**Comment by neic** [comment]
[django-wiki](https://github.com/django-wiki/django-wiki) er en markdown wiki. Den har indbygget adgangs kontrol på side-niveau baseret på django grupper og brugere. Jeg har installeret det uden nogen videre opsætning og prøvet at lave en HSTR-side og en TK-grill side med BEST og hænger adgang. Det virker bare! 👍 

Det er under aktiv udvikling. Dokumentationen er ikke vild god.

----

Jeg har, ved at tillade nogle flere attributter i sanitizationen, fået Bootstraps `collapse.js` til at virke så man kan lave knapper der skjuler og viser indhold. `django-wiki` har [et plugin](https://github.com/django-wiki/django-wiki/tree/master/src/wiki/plugins/macros) der implementere et par markdown makroer som indholdsfortegnelse `[TOC]`. Vi kan sikkert lave en tilsvarende makro der pakker `collapse.js` fint ind. Jeg tænker noget i stil med `[skjult KASS Her står noget information til KASS.]`.

Adgangs kontrollen er lavet med to grupper `BEST` og `Hængere`. På hver artikel sættes en gruppe som har læse og skrive adgang. Læse og skrive adgang fjernes for "andre". En BEST bruger er medlem af både `BEST` og `Hængere`. Andre er medlem af `Hængere`. Der kan laves nedarvninger fra side til side.

Umiddelbare mangler er:
- En måde at flagge artikler på der skal opdateres. Samt at få en liste over dem.
- Hemmelige sektioner. (Som kan blive svært)
- [`tktitler`](https://github.com/TK-IT/tktitler) integration. (Her kan makroerne sikkert også bruges.)

**Comment by neic** [comment]
Med det helt nye PR https://github.com/django-wiki/django-wiki/pull/840 kan vi lave hemmelige sektioner synlige for nogle personer.

**Comment by benjaoming** [comment]
> Dokumentationen er ikke vild god.

Til gengæld er den næsten 100% oversat til dansk ;)

Kom bare med Pull-Requests, hvis I har ideer til dokumentationen!

**Comment by neic** [comment]
Jeg har lavet [en milestone](https://github.com/TK-IT/web/milestone/8) i web repoet til at tracke fremgangen.

**Comment by benjaoming** [comment]
@neic gør lige lidt reklame for dansk Django begivenhed: https://djangocph.dk/

**Comment by neic** [comment]
@benjaoming Tak. Det lyder interessant. Det kan være at jeg kigger forbi :)

**Comment by benjaoming** [comment]
Du/I skal være så velkom(men/ne)! :)
